import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} active`} id="top">
        <Header />
        {children}
        <Footer />

        {/* Back to top */}
        <a
          href="#top"
          className="back_top_btn"
          aria-label="back to top"
          data-back-top-btn
        >
          0%
        </a>

        {/* Custom Cursor */}
        <div className="cursor" data-cursor></div>
      </body>
    </html>
  );
}
